# Generated by Django 5.0.1 on 2024-02-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hotelbooking_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='rooms',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
