# Generated by Django 5.0.1 on 2024-02-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resortbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resortbooking',
            old_name='Hotel',
            new_name='Resort',
        ),
    ]
