# Generated by Django 5.0.1 on 2024-02-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_date_hotelbooking_checkindate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='CheckInDate',
            new_name='CheckIn',
        ),
        migrations.RenameField(
            model_name='resortbooking',
            old_name='CheckInDate',
            new_name='CheckIn',
        ),
    ]
