# Generated by Django 5.0.1 on 2024-02-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hotelbooking_payment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpayment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='resortpayment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resortbooking'),
        ),
    ]
